server:
  port: 8085

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: order-events
  queues:
    order-created: notification-order-created
    order-paid: notification-order-paid
    order-shipped: notification-order-shipped

logging:
  level:
    com.platform.notification: DEBUG
