apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: order-platform
data:
  # PostgreSQL
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  
  # RabbitMQ
  RABBITMQ_HOST: rabbitmq-service
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: guest
  
  # Service URLs
  AUTH_SERVICE_URL: http://auth-service:8081
  CATALOG_SERVICE_URL: http://catalog-service:8082
  INVENTORY_SERVICE_URL: http://inventory-service:8083
  ORDER_SERVICE_URL: http://order-service:8084
  NOTIFICATION_SERVICE_URL: http://notification-service:8085
