apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: order-platform
type: Opaque
data:
  # Base64 encoded values (use: echo -n 'value' | base64)
  # postgres / postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # guest
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  # your-secret-key-change-this-in-production-min-256-bits-long
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24tbWluLTI1Ni1iaXRzLWxvbmc=
